import { requireAuth } from "@/lib/auth";
import BankAccountModel from "@/models/BankAccount";
import CreditCardModel from "@/models/CreditCard";
const modes = ["Cash", "UPI", "Debit Card", "Credit Card", "Bank Transfer"] as const;
type Input = { amount?: unknown; source?: unknown; category?: unknown; date?: unknown; paymentMode?: unknown; bankAccount?: unknown; creditCard?: unknown; note?: unknown };
export type ExpenseRecord = { id: string; amount: number; source?: string; category: string; date: string; paymentMode: string; bankAccount?: string | null; creditCard?: string | null; note?: string };
export const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
export function parseExpense(input: Input, partial = false) { const values: Record<string, unknown> = {}; if (!partial || input.amount !== undefined) { const amount = Number(input.amount); if (!Number.isFinite(amount) || amount <= 0) throw new Error("Amount must be greater than zero."); values.amount = amount; } if (!partial || input.category !== undefined) { const category = text(input.category); if (!category) throw new Error("Category is required."); values.category = category; } if (!partial || input.date !== undefined) { const date = new Date(text(input.date)); if (Number.isNaN(date.getTime())) throw new Error("A valid date is required."); values.date = date; } if (!partial || input.paymentMode !== undefined) { const paymentMode = text(input.paymentMode); if (!modes.includes(paymentMode as (typeof modes)[number])) throw new Error("Choose a valid payment mode."); values.paymentMode = paymentMode; } if (input.source !== undefined || !partial) values.source = text(input.source) || undefined; if (input.note !== undefined || !partial) values.note = text(input.note) || undefined; if (input.bankAccount !== undefined || !partial) values.bankAccount = text(input.bankAccount) || undefined; if (input.creditCard !== undefined || !partial) values.creditCard = text(input.creditCard) || undefined; return values; }
export const serializeExpense = (entry: { _id: { toString(): string }; amount: number; source?: string; category: string; date: Date; paymentMode: string; bankAccount?: { toString(): string } | null; creditCard?: { toString(): string } | null; note?: string }): ExpenseRecord => ({ id: entry._id.toString(), amount: entry.amount, source: entry.source, category: entry.category, date: entry.date.toISOString(), paymentMode: entry.paymentMode, bankAccount: entry.bankAccount?.toString() ?? null, creditCard: entry.creditCard?.toString() ?? null, note: entry.note });
export async function getUserId() { const session = await requireAuth(); if (typeof session.userId !== "string") throw new Error("Unauthorized"); return session.userId; }
export async function ensureBankAccount(userId: string, value?: unknown) { const id = text(value); if (!id) return undefined; if (!await BankAccountModel.exists({ _id: id, user: userId })) throw new Error("The selected bank account was not found."); return id; }
export async function ensureCreditCard(userId: string, value?: unknown) { const id = text(value); if (!id) return undefined; if (!await CreditCardModel.exists({ _id: id, user: userId })) throw new Error("The selected credit card was not found."); return id; }
