import { requireAuth } from "@/lib/auth";
import BankAccountModel from "@/models/BankAccount";
const modes = ["Cash", "Bank Transfer", "UPI", "Other"] as const;
type Input = { amount?: unknown; source?: unknown; category?: unknown; date?: unknown; note?: unknown; paymentMode?: unknown; bankAccount?: unknown };
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
export function parseIncome(input: Input, partial = false) { const values: Record<string, unknown> = {}; if (!partial || input.amount !== undefined) { const amount = Number(input.amount); if (!Number.isFinite(amount) || amount <= 0) throw new Error("Amount must be greater than zero."); values.amount = amount; } if (!partial || input.source !== undefined) { const source = text(input.source); if (!source) throw new Error("Source is required."); values.source = source; } if (!partial || input.date !== undefined) { const date = new Date(text(input.date)); if (Number.isNaN(date.getTime())) throw new Error("A valid date is required."); values.date = date; } if (!partial || input.paymentMode !== undefined) { const paymentMode = text(input.paymentMode); if (!modes.includes(paymentMode as (typeof modes)[number])) throw new Error("Choose a valid payment mode."); values.paymentMode = paymentMode; } if (input.category !== undefined || !partial) values.category = text(input.category) || undefined; if (input.note !== undefined || !partial) values.note = text(input.note) || undefined; if (input.bankAccount !== undefined || !partial) values.bankAccount = text(input.bankAccount) || undefined; return values; }
export function serializeIncome(entry: { _id: { toString(): string }; amount: number; source: string; category?: string; date: Date; note?: string; paymentMode: string; bankAccount?: { _id?: { toString(): string }; toString(): string } | null }) { const bankAccount = entry.bankAccount && typeof entry.bankAccount === "object" && "_id" in entry.bankAccount ? entry.bankAccount._id?.toString() : entry.bankAccount?.toString(); return { id: entry._id.toString(), amount: entry.amount, source: entry.source, category: entry.category, date: entry.date.toISOString(), note: entry.note, paymentMode: entry.paymentMode, bankAccount: bankAccount ?? null }; }
export async function getUserId() { const session = await requireAuth(); if (typeof session.userId !== "string") throw new Error("Unauthorized"); return session.userId; }
export async function ensureBankAccount(userId: string, bankAccount?: unknown) { const id = text(bankAccount); if (!id) return undefined; if (!await BankAccountModel.findOne({ _id: id, user: userId }).select("_id").lean()) throw new Error("The selected bank account was not found."); return id; }
export { text };
