"use client";
import * as React from "react";
import { format } from "date-fns";
import { ArrowDownRight, ArrowUpRight, Building2, ChevronLeft, Landmark, Plus, ReceiptText, Trash2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import EmptyState from "@/components/finance/EmptyState";
import MoneyText from "@/components/finance/MoneyText";
import StatCard from "@/components/finance/StatCard";
import useCountUp from "@/hooks/useCountUp";
import LoaderOverlay from "@/components/loader/LoaderOverlay";
import PageSkeleton from "@/components/loader/PageSkeleton";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { type BankAccount, type BankAccountInput, type BankTransaction, useBankAccounts } from "@/hooks/useBankAccounts";
const COLORS = ["#1e3a5f", "#0f766e", "#6d28d9", "#9a3412", "#9f1239", "#334155"];
const today = () => format(new Date(), "yyyy-MM-dd");
const emptyAccount = (): BankAccountInput => ({ bankName: "", accountName: "", accountType: "Savings", last4Digits: "", openingBalance: 0, themeColor: COLORS[0] });
export default function BankAccountsPage() { const { accounts, isLoading, isMutating, create, remove, transaction } = useBankAccounts(); const [selected, setSelected] = React.useState<BankAccount | null>(null); const [ledger, setLedger] = React.useState<BankTransaction[]>([]); const [accountOpen, setAccountOpen] = React.useState(false); const [transactionOpen, setTransactionOpen] = React.useState(false); const [accountForm, setAccountForm] = React.useState<BankAccountInput>(emptyAccount()); const [transactionForm, setTransactionForm] = React.useState({ type: "Credit" as "Credit" | "Debit", amount: "", description: "", date: today() }); const total = accounts.reduce((sum, account) => sum + account.currentBalance, 0);
  async function openAccount(account: BankAccount) { setSelected(account); try { const payload = await read(fetch(`/api/bank-accounts/${account.id}/transactions`)); setLedger(payload.transactions); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load transaction history."); } }
  async function submitAccount(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); try { await create(accountForm); toast.success("Bank account added."); setAccountOpen(false); setAccountForm(emptyAccount()); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to add account."); } }
  async function submitTransaction(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const amount = Number(transactionForm.amount); if (!Number.isFinite(amount) || amount <= 0) return toast.error("Enter a valid amount."); try { await transaction(selected.id, { ...transactionForm, amount, date: new Date(`${transactionForm.date}T12:00:00`).toISOString() }); toast.success("Transaction added."); setTransactionOpen(false); setTransactionForm({ type: "Credit", amount: "", description: "", date: today() }); await openAccount({ ...selected, currentBalance: selected.currentBalance + (transactionForm.type === "Credit" ? amount : -amount) }); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to add transaction."); } }
  async function deleteAccount(account: BankAccount) { if (!window.confirm(`Delete ${account.accountName || account.bankName}?`)) return; try { await remove(account.id); toast.success("Bank account deleted."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to delete account."); } }
  if (isLoading) return <PageSkeleton variant="table" />;
  if (selected) return <div className="space-y-6"><Button variant="ghost" className="-ml-3" onClick={() => setSelected(null)}><ChevronLeft />All accounts</Button><AccountVisual account={selected} className="max-w-md" /><div className="flex items-center justify-between"><div><h2 className="font-heading text-2xl font-semibold">{selected.accountName || selected.bankName}</h2><p className="text-sm text-muted-foreground">{selected.bankName} · {selected.accountType}</p></div><Button onClick={() => setTransactionOpen(true)}><Plus />Add Transaction</Button></div><div className="card overflow-hidden"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Description</TableHead><TableHead>Source</TableHead><TableHead>Type</TableHead><TableHead className="text-right">Amount</TableHead><TableHead className="text-right">Balance</TableHead></TableRow></TableHeader><TableBody>{ledger.map((item) => <TableRow key={item.id}><TableCell>{format(new Date(item.date), "dd MMM yyyy")}</TableCell><TableCell className="font-medium">{item.description || "Transaction"}</TableCell><TableCell><span className="rounded-full bg-muted px-2 py-1 text-xs">{item.source}</span></TableCell><TableCell className={item.type === "Credit" ? "text-income" : "text-expense"}>{item.type}</TableCell><TableCell className="text-right"><MoneyText value={item.amount} variant={item.type === "Credit" ? "positive" : "negative"} /></TableCell><TableCell className="text-right"><MoneyText value={item.balanceAfter ?? 0} /></TableCell></TableRow>)}{!ledger.length && <TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">No transactions recorded yet.</TableCell></TableRow>}</TableBody></Table></div><TransactionDialog open={transactionOpen} onOpenChange={setTransactionOpen} form={transactionForm} setForm={setTransactionForm} onSubmit={submitTransaction} /><LoaderOverlay show={isMutating} label="Updating account..." /></div>;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-heading text-2xl font-semibold">Bank Accounts</h2><p className="mt-1 text-sm text-muted-foreground">A single, up-to-date view of your cash across every account.</p></div><Button onClick={() => setAccountOpen(true)}><Plus />Add Account</Button></div><div className="max-w-sm"><StatCard icon={<Landmark />} label="Total Balance" value={total} /></div>{accounts.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{accounts.map((account) => <div key={account.id} className="group relative"><button className="w-full text-left" onClick={() => void openAccount(account)}><AccountVisual account={account} /></button><Button variant="ghost" size="icon-sm" className="absolute bottom-3 right-3 text-white/80 hover:bg-white/15 hover:text-white" onClick={() => void deleteAccount(account)} aria-label="Delete account"><Trash2 /></Button></div>)}</div> : <EmptyState icon={<Building2 />} title="No bank accounts yet" description="Add an account to see your balances and transaction history in one place." action={<Button onClick={() => setAccountOpen(true)}><Plus />Add your first bank account</Button>} />}<AccountDialog open={accountOpen} onOpenChange={setAccountOpen} form={accountForm} setForm={setAccountForm} onSubmit={submitAccount} /><LoaderOverlay show={isMutating} label="Updating bank accounts..." /></div>;
}
async function read(response: Response | Promise<Response>) { const result = await response; const payload = await result.json(); if (!result.ok) throw new Error(payload.error ?? "Something went wrong."); return payload; }
function AccountVisual({ account, className = "" }: { account: BankAccount; className?: string }) { const balance = useCountUp(account.currentBalance, 700); const color = account.themeColor || COLORS[0]; return <div className={`relative aspect-[1.62/1] overflow-hidden rounded-2xl p-5 text-white shadow-lg transition-transform group-hover:-translate-y-1 ${className}`} style={{ background: `linear-gradient(135deg, ${color}, color-mix(in srgb, ${color} 52%, black))` }}><div className="absolute -right-8 -top-12 size-44 rounded-full border border-white/15" /><div className="absolute -bottom-20 left-10 size-44 rounded-full border border-white/10" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><Building2 /><span className="rounded-full bg-white/15 px-2 py-1 text-xs">{account.accountType}</span></div><div className="mt-auto"><p className="text-sm text-white/70">Current balance</p><MoneyText value={balance} className="mt-1 text-3xl font-bold tracking-tight" /><div className="mt-4 flex justify-between text-xs uppercase tracking-wider text-white/75"><span>{account.accountName || account.bankName}</span><span>•••• {account.last4Digits || "----"}</span></div></div></div></div> }
function AccountDialog({ open, onOpenChange, form, setForm, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; form: BankAccountInput; setForm: React.Dispatch<React.SetStateAction<BankAccountInput>>; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { const change = <K extends keyof BankAccountInput>(key: K, value: BankAccountInput[K]) => setForm((current) => ({ ...current, [key]: value })); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Add bank account</DialogTitle><DialogDescription>Set an opening balance to start a complete account ledger.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={onSubmit}><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label>Bank name</Label><Input value={form.bankName} onChange={(event) => change("bankName", event.target.value)} required /></div><div className="grid gap-2"><Label>Account nickname</Label><Input value={form.accountName || ""} onChange={(event) => change("accountName", event.target.value)} placeholder="Everyday savings" /></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label>Account type</Label><Select value={form.accountType} onValueChange={(value) => change("accountType", (value ?? "Savings") as BankAccountInput["accountType"])}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Savings">Savings</SelectItem><SelectItem value="Current">Current</SelectItem><SelectItem value="Other">Other</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Last 4 digits</Label><Input value={form.last4Digits || ""} maxLength={4} inputMode="numeric" onChange={(event) => change("last4Digits", event.target.value.replace(/\D/g, ""))} /></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label>Opening balance</Label><Input type="number" step="0.01" value={form.openingBalance || ""} onChange={(event) => change("openingBalance", Number(event.target.value))} required /></div><div className="grid gap-2"><Label>Theme color</Label><div className="flex gap-2">{COLORS.map((color) => <button key={color} type="button" className={`size-8 rounded-full ring-offset-2 ${form.themeColor === color ? "ring-2 ring-primary" : ""}`} style={{ backgroundColor: color }} onClick={() => change("themeColor", color)} aria-label={`Select ${color}`} />)}</div></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit">Add account</Button></DialogFooter></form></DialogContent></Dialog> }
function TransactionDialog({ open, onOpenChange, form, setForm, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; form: { type: "Credit" | "Debit"; amount: string; description: string; date: string }; setForm: React.Dispatch<React.SetStateAction<{ type: "Credit" | "Debit"; amount: string; description: string; date: string }>>; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { const change = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value })); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add transaction</DialogTitle><DialogDescription>Add a cash deposit, withdrawal, or other manual movement.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={onSubmit}><div className="grid gap-2"><Label>Type</Label><div className="grid grid-cols-2 gap-2"><Button type="button" variant={form.type === "Credit" ? "default" : "outline"} onClick={() => change("type", "Credit")}><ArrowUpRight />Credit</Button><Button type="button" variant={form.type === "Debit" ? "default" : "outline"} onClick={() => change("type", "Debit")}><ArrowDownRight />Debit</Button></div></div><div className="grid gap-2"><Label>Amount</Label><Input type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => change("amount", event.target.value)} required /></div><div className="grid gap-2"><Label>Description</Label><Input value={form.description} onChange={(event) => change("description", event.target.value)} placeholder="Cash deposit" required /></div><div className="grid gap-2"><Label>Date</Label><Input type="date" value={form.date} onChange={(event) => change("date", event.target.value)} required /></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit"><ReceiptText />Add transaction</Button></DialogFooter></form></DialogContent></Dialog> }
