import { NextRequest, NextResponse } from "next/server";

import { requireAuth } from "@/lib/auth";
import connect from "@/lib/db";
import CreditCardBillModel from "@/models/CreditCardBill";
import CreditCardModel from "@/models/CreditCard";
import CreditCardTransactionModel from "@/models/CreditCardTransaction";

type CardInput = { cardName?: unknown; bankName?: unknown; last4Digits?: unknown; billingCycleDay?: unknown; dueDay?: unknown; creditLimit?: unknown; themeColor?: unknown };
export type CardRecord = { id: string; cardName: string; bankName: string; last4Digits: string; billingCycleDay: number; dueDay: number; creditLimit: number; themeColor?: string; outstanding: number; availableCredit: number };
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function day(value: unknown, label: string) { const number = Number(value); if (!Number.isInteger(number) || number < 1 || number > 31) throw new Error(`${label} must be between 1 and 31.`); return number; }
export function parseCard(input: CardInput, partial = false) { const values: Record<string, unknown> = {}; if (!partial || input.cardName !== undefined) { const value = text(input.cardName); if (!value) throw new Error("Card name is required."); values.cardName = value; } if (!partial || input.bankName !== undefined) { const value = text(input.bankName); if (!value) throw new Error("Bank name is required."); values.bankName = value; } if (!partial || input.last4Digits !== undefined) { const value = text(input.last4Digits); if (!/^\d{4}$/.test(value)) throw new Error("Enter the last four card digits."); values.last4Digits = value; } if (!partial || input.billingCycleDay !== undefined) values.billingCycleDay = day(input.billingCycleDay, "Billing cycle day"); if (!partial || input.dueDay !== undefined) values.dueDay = day(input.dueDay, "Due day"); if (!partial || input.creditLimit !== undefined) { const value = Number(input.creditLimit); if (!Number.isFinite(value) || value <= 0) throw new Error("Credit limit must be greater than zero."); values.creditLimit = value; } if (input.themeColor !== undefined || !partial) values.themeColor = text(input.themeColor) || undefined; return values; }
export async function getUserId() { const session = await requireAuth(); if (typeof session.userId !== "string") throw new Error("Unauthorized"); return session.userId; }
export function serializeCard(card: { _id: { toString(): string }; cardName: string; bankName: string; last4Digits: string; billingCycleDay: number; dueDay: number; creditLimit: number; themeColor?: string }, outstanding = 0): CardRecord { return { id: card._id.toString(), cardName: card.cardName, bankName: card.bankName, last4Digits: card.last4Digits, billingCycleDay: card.billingCycleDay, dueDay: card.dueDay, creditLimit: card.creditLimit, themeColor: card.themeColor, outstanding, availableCredit: Math.max(card.creditLimit - outstanding, 0) }; }

export async function GET() { try { await connect(); const userId = await getUserId(); const [cards, currentCycle, unpaidBills] = await Promise.all([CreditCardModel.find({ user: userId }).sort({ createdAt: -1 }).lean(), CreditCardTransactionModel.aggregate([{ $match: { user: (await import("mongoose")).default.Types.ObjectId.createFromHexString(userId), billed: false } }, { $group: { _id: "$creditCard", total: { $sum: "$amount" } } }]), CreditCardBillModel.aggregate([{ $match: { user: (await import("mongoose")).default.Types.ObjectId.createFromHexString(userId), isPaid: false } }, { $group: { _id: "$creditCard", total: { $sum: "$totalAmount" } } }])]); const outstanding = new Map<string, number>(); [...currentCycle, ...unpaidBills].forEach((item) => outstanding.set(item._id.toString(), (outstanding.get(item._id.toString()) ?? 0) + item.total)); return NextResponse.json({ cards: cards.map((card) => serializeCard(card, outstanding.get(card._id.toString()) ?? 0)) }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load credit cards." }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { await connect(); const userId = await getUserId(); const card = await CreditCardModel.create({ ...parseCard(await request.json()), user: userId }); return NextResponse.json({ card: serializeCard(card) }, { status: 201 }); } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create credit card." }, { status: 400 }); } }
