import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import connect from "@/lib/db";
import BankAccountModel from "@/models/BankAccount";

const TYPES = ["Savings", "Current", "Other"] as const;
type Input = { bankName?: unknown; accountName?: unknown; accountType?: unknown; last4Digits?: unknown; openingBalance?: unknown; themeColor?: unknown };
export type AccountRecord = { id: string; bankName: string; accountName?: string; accountType: "Savings" | "Current" | "Other"; last4Digits?: string; currentBalance: number; openingBalance: number; themeColor?: string };
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
export function parseAccount(input: Input, partial = false) { const values: Record<string, unknown> = {}; if (!partial || input.bankName !== undefined) { const bankName = text(input.bankName); if (!bankName) throw new Error("Bank name is required."); values.bankName = bankName; } if (!partial || input.accountType !== undefined) { const accountType = text(input.accountType); if (!TYPES.includes(accountType as (typeof TYPES)[number])) throw new Error("Choose a valid account type."); values.accountType = accountType; } if (!partial || input.openingBalance !== undefined) { const openingBalance = Number(input.openingBalance); if (!Number.isFinite(openingBalance)) throw new Error("Opening balance must be valid."); values.openingBalance = openingBalance; } if (input.accountName !== undefined || !partial) values.accountName = text(input.accountName) || undefined; if (input.last4Digits !== undefined || !partial) { const last4Digits = text(input.last4Digits); if (last4Digits && !/^\d{4}$/.test(last4Digits)) throw new Error("Last four digits must contain four numbers."); values.last4Digits = last4Digits || undefined; } if (input.themeColor !== undefined || !partial) values.themeColor = text(input.themeColor) || undefined; return values; }
export const serializeAccount = (item: { _id: { toString(): string }; bankName: string; accountName?: string; accountType: AccountRecord["accountType"]; last4Digits?: string; currentBalance: number; openingBalance?: number; themeColor?: string }): AccountRecord => ({ id: item._id.toString(), bankName: item.bankName, accountName: item.accountName, accountType: item.accountType, last4Digits: item.last4Digits, currentBalance: item.currentBalance, openingBalance: item.openingBalance ?? 0, themeColor: item.themeColor });
export async function getUserId() { const session = await requireAuth(); if (typeof session.userId !== "string") throw new Error("Unauthorized"); return session.userId; }
export async function GET() { try { await connect(); const accounts = await BankAccountModel.find({ user: await getUserId() }).sort({ updatedAt: -1 }).lean(); return NextResponse.json({ accounts: accounts.map(serializeAccount) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to load bank accounts." }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { await connect(); const input = parseAccount(await request.json()); const account = await BankAccountModel.create({ ...input, user: await getUserId(), currentBalance: input.openingBalance as number }); return NextResponse.json({ account: serializeAccount(account) }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create bank account." }, { status: 400 }); } }
