// @ts-nocheck
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireAuth } from "@/lib/auth";
import connect from "@/lib/db";
import BankAccountModel from "@/models/BankAccount";
import BankTransactionModel from "@/models/BankTransaction";
import ExpenseModel from "@/models/Expense";
import IncomeModel from "@/models/Income";
import InvestmentModel from "@/models/Investment";
import LendingModel from "@/models/Lending";

const date = z.coerce.date(); const amount = z.coerce.number().positive(); const optional = z.string().optional().transform((value) => value?.trim() || undefined);
const schemas = {
  income: z.object({ Amount: amount, Source: z.string().min(1), Category: optional, Date: date, Note: optional, "Payment Mode": z.enum(["Cash", "Bank Transfer", "UPI", "Other"]).default("Cash") }),
  expense: z.object({ Amount: amount, Source: optional, Category: z.string().min(1), Date: date, Note: optional, "Payment Mode": z.enum(["Cash", "UPI", "Debit Card", "Credit Card", "Bank Transfer"]).default("Cash") }),
  investment: z.object({ Type: z.enum(["Mutual Fund", "Stocks", "FD", "RD", "Gold", "Crypto", "PPF", "Other"]), Name: optional, "Amount Invested": amount, "Current Value": z.coerce.number().nonnegative().optional(), Date: date, Note: optional }),
  lending: z.object({ Person: z.string().min(1), Type: z.enum(["Given", "Taken"]), Amount: amount, "Amount Returned": z.coerce.number().nonnegative().default(0), Date: date, "Due Date": z.union([date, z.literal(""), z.undefined()]).optional(), Note: optional }),
  "bank-transactions": z.object({ "Bank Name": z.string().min(1), "Account Name": optional, "Account Type": z.enum(["Savings", "Current", "Other"]).default("Savings"), "Last 4 Digits": optional, "Opening Balance": z.coerce.number().default(0), Type: z.enum(["Credit", "Debit"]).optional(), Amount: z.coerce.number().positive().optional(), Description: optional, Date: z.union([date, z.literal(""), z.undefined()]).optional() }),
} as const;
type Module = keyof typeof schemas;
export async function POST(request: NextRequest, context: RouteContext<"/api/import/[module]">) { try { await connect(); const session = await requireAuth(); if (typeof session.userId !== "string") throw new Error("Unauthorized"); const { module } = await context.params; if (!(module in schemas)) return NextResponse.json({ error: "Unsupported import module." }, { status: 404 }); const body = await request.json(); if (!Array.isArray(body.rows)) throw new Error("Rows are required."); const parsed = body.rows.map((row: unknown, index: number) => ({ index: index + 2, value: schemas[module as Module].safeParse(row) })); const invalid = parsed.filter((item) => !item.value.success).map((item) => ({ row: item.index, reason: item.value.error.issues[0]?.message ?? "Invalid row" })); const rows = parsed.filter((item): item is { index: number; value: { success: true; data: never } } => item.value.success).map((item) => item.value.data);
    if (module === "income") await IncomeModel.insertMany(rows.map((row) => ({ user: session.userId, amount: row.Amount, source: row.Source, category: row.Category, date: row.Date, note: row.Note, paymentMode: row["Payment Mode"] })));
    if (module === "expense") await ExpenseModel.insertMany(rows.map((row) => ({ user: session.userId, amount: row.Amount, source: row.Source, category: row.Category, date: row.Date, note: row.Note, paymentMode: row["Payment Mode"] })));
    if (module === "investment") await InvestmentModel.insertMany(rows.map((row) => ({ user: session.userId, type: row.Type, name: row.Name, amountInvested: row["Amount Invested"], currentValue: row["Current Value"] ?? row["Amount Invested"], date: row.Date, note: row.Note })));
    if (module === "lending") await LendingModel.insertMany(rows.map((row) => { const returned = Math.min(row["Amount Returned"], row.Amount); return { user: session.userId, person: row.Person, type: row.Type, amount: row.Amount, amountReturned: returned, status: returned >= row.Amount ? "Settled" : returned > 0 ? "Partially Returned" : "Pending", date: row.Date, dueDate: row["Due Date"] || undefined, note: row.Note }; }));
    if (module === "bank-transactions") { const accounts = new Map<string, { _id: unknown; currentBalance: number }>(); const existing = await BankAccountModel.find({ user: session.userId }).lean(); existing.forEach((account) => accounts.set(`${account.bankName}|${account.accountName || ""}`, { _id: account._id, currentBalance: account.currentBalance })); const newAccounts = rows.filter((row) => !accounts.has(`${row["Bank Name"]}|${row["Account Name"] || ""}`)).map((row) => ({ user: session.userId, bankName: row["Bank Name"], accountName: row["Account Name"], accountType: row["Account Type"], last4Digits: row["Last 4 Digits"], openingBalance: row["Opening Balance"], currentBalance: row["Opening Balance"] })); if (newAccounts.length) { const inserted = await BankAccountModel.insertMany(newAccounts); inserted.forEach((account) => accounts.set(`${account.bankName}|${account.accountName || ""}`, { _id: account._id, currentBalance: account.currentBalance })); } const transactions: Record<string, unknown>[] = []; for (const row of rows) { if (!row.Type || !row.Amount) continue; const key = `${row["Bank Name"]}|${row["Account Name"] || ""}`; const account = accounts.get(key)!; account.currentBalance += row.Type === "Credit" ? row.Amount : -row.Amount; transactions.push({ user: session.userId, bankAccount: account._id, type: row.Type, amount: row.Amount, description: row.Description, date: row.Date || new Date(), source: "Manual", balanceAfter: account.currentBalance }); } if (transactions.length) await BankTransactionModel.insertMany(transactions); await Promise.all([...accounts.values()].map((account) => BankAccountModel.updateOne({ _id: account._id }, { currentBalance: account.currentBalance }))); }
    return NextResponse.json({ inserted: rows.length, failed: invalid.length, failures: invalid });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Import failed." }, { status: 400 }); } }
